# TODO: make Singleton
class Acronyms:

    acronyms = {

    'BD':   'big deal',
    'BF':   'boyfriend',
    'BRB':  'be right back',
    'BTW':  'by the way',
    'GF':   'girlfriend',
    'HBD':  'happy birthday',
    'JK':   'just kidding',
    'KK':   'cool',
    'LMK':  'let me know',
    'LOL':  'laugh out loud',
    'MYOB': 'mind your own business',
    'NBD':  'no big deal',
    'NVM':  'nevermind',
    'OBV':  'obviously',
    'OBVI': 'obviously',
    'OMG':  'oh my God',
    'PLS':  'please',
    'PLZ':  'please',
    'QQ':   'quick question',
    'RLY':  'really',
    'SRLSY':'seriously',
    'TMI':  'too much information',
    'TY':   'thank you',
    'TYVM': 'thank you very much',
    'YW':   'you are welcome',
    'FOMO': 'fear of missing out',
    'FTFY': 'fixed this for you',
    'FTW':  'for the win',
    'FYA':  'for your amusement',
    'FYE':  'for your entertainment',
    'GTI':  'going through it',
    'HTH':  'here to help',
    'IRL':  'in real life',
    'ICYMI': 'in case you missed it',
    'ICYWW': 'in case you were wondering',
    'NBC':  'nobody cares though',
    'NTW':  'not to worry',
    'OTD':  'of the day',
    'OOTD': 'outfit of the day',
    'QOTD': 'quote of the day',
    'FOTD': 'find of the day',
    'YOLO': 'you only live once',
    'ZOMG': 'oh my god, but, like, more emphatic',
    'AFAIK': 'as far as i Know',
    'DGYF': 'dang girl you fine',
    'FWIW': 'for what it\'s worth',
    'IDC': 'i don\'t care',
    'IDK': 'i don\'t know',
    'FYI':  'for your information',
    'IIRC': 'if i remember correctly',
    'IMHO': 'in my honest opinion',
    'IMO':  'in my opinion',
    'JELL': 'jealous',
    'JSYK': 'just so you know',
    'LMAO': 'laughing my ass off',
    'LMFAO': 'laughing my fucking ass off',
    'NTS':  'note to self',
    'ROFL': 'rolling on the floor laughing',
    'ROFLMAO': 'rolling on the floor laughing my ass off',
    'SMH':  'shaking my head',
    'TBH':  'to be honest',
    'TL':   'too long',
    'DR':   'didn\'t read',
    'YGTR': 'you got that right',
    'AYKMWTS': 'are you kidding me with this shit?',
    'BAMF': 'bad ass mother fucker',
    'FFS':  'for fuckin\'s sake',
    'FML':  'fuck my life',
    'HYFR': 'hell yeah fucking right',
    'IDGAF': 'i don\'t give a fuck',
    'NFW':  'no fucking way',
    'PITA': 'pain in the ass',
    'POS':  'piece of shit',
    'SOL':  'shit outta luck',
    'STFU': 'shut the fuck up',
    'TF':   'the fuck',
    'WTF':  'What The Fuck',
    'BFN':  'bye for now',
    'CU':   'see you',
    'CYL':  'see you later',
    'GTG':  'got to go',
    'OMW':  'on my way',
    'RN':   'right now',
    'TTYL': 'talk to you later',
    'TYT':  'take your time',
    'CC':   'carbon copy',
    'CX':   'correction',
    'DM':   'direct message',
    'FB':   'facebook',
    '#FBF': 'flash-back friday',
    '#FF':  'follow friday',
    'HT':   'hat tip',
    'IG':   'instagram',
    'MT':   'modified tweet',
    'OH':   'overheard',
    'PRT':  'partial retweet',
    'RT':   'retweet',
    'SO':   'shout out',
    'AWOL': 'away while online',
    'BFF': 'best friend forever',
    'NSFW': 'not safe for work',
    'OG':   'original gangster',
    'PSA':  'public service announcement',
    'PDA': 'public display of affection',
    '#TBT': 'throw-back thursday'
    }


    def getAcronyms(self):
        return self.acronyms