
class Acronyms:

    acronyms = {

    'BD':   'Big Deal',
    'BF':   'Boyfriend',
    'BRB':  'Be Right Back',
    'BTW':  'By The Way',
    'GF':   'Girlfriend',
    'HBD':  'Happy Birthday',
    'JK':   'Just Kidding',
    'KK':   'Cool',
    'LMK':  'Let Me Know',
    'LOL':  'Laugh Out Loud',
    'MYOB': 'Mind Your Own Business',
    'NBD':  'No Big Deal',
    'NVM':  'Nevermind',
    'OBV':  'Obviously',
    'OBVI': 'Obviously',
    'OMG':  'Oh My God',
    'PLS':  'Please',
    'PLZ':  'Please',
    'QQ':   'Quick Question',
    'RLY':  'Really',
    'SRLSY':'Seriously',
    'TMI':  'Too Much Information',
    'TY':   'Thank You',
    'TYVM': 'Thank You Very Much',
    'YW':   'You are Welcome',
    'FOMO': 'Fear Of Missing Out',
    'FTFY': 'Fixed This For You',
    'FTW':  'For The Win',
    'FYA':  'For Your Amusement',
    'FYE':  'For Your Entertainment',
    'GTI':  'Going Through It',
    'HTH':  'Here to Help',
    'IRL':  'In Real Life',
    'ICYMI': 'In Case You Missed It',
    'ICYWW': 'In Case You Were Wondering',
    'NBC':  'Nobody Cares Though',
    'NTW':  'Not To Worry',
    'OTD':  'Of The Day',
    'OOTD': 'Outfit Of The Day',
    'QOTD': 'Quote of the Day',
    'FOTD': 'Find Of the Day',
    'YOLO': 'You Only Live Once',
    'ZOMG': 'Oh My God, but, like, more emphatic',
    'AFAIK': 'As Far As I Know',
    'DGYF': 'Dang Girl You Fine',
    'FWIW': 'For What It\'s Worth',
    'IDC': 'I Don\'t Care',
    'IDK': 'I Don\'t Know',
    'FYI':  'For Your Information',
    'IIRC': 'If I Remember Correctly',
    'IMHO': 'In My Honest Opinion',
    'IMO':  'In My Opinion',
    'JELL': 'Jealous',
    'JSYK': 'Just So You Know',
    'LMAO': 'Laughing My Ass Off',
    'LMFAO': 'Laughing My Fucking Ass Off',
    'NTS':  'Note to Self',
    'ROFL': 'Rolling On the Floor Laughing',
    'ROFLMAO': 'Rolling On the Floor Laughing My Ass Off',
    'SMH':  'Shaking My Head',
    'TBH':  'To Be Honest',
    'TL':   'Too Long',
    'DR':   'Didn\'t read',
    'YGTR': 'You Got That Right',
    'AYKMWTS': 'Are You Kidding Me With This Shit?',
    'BAMF': 'Bad Ass Mother Fucker',
    'FFS':  'For Fuckin\'s Sake',
    'FML':  'Fuck My Life',
    'HYFR': 'Hell yeah Fucking Right',
    'IDGAF': 'I Don\'t Give A Fuck',
    'NFW':  'No Fucking Way',
    'PITA': 'Pain In The Ass',
    'POS':  'Piece of Shit',
    'SOL':  'Shit Outta Luck',
    'STFU': 'Shut the Fuck Up',
    'TF':   'The Fuck',
    'WTF':  'What The Fuck',
    'BFN':  'Bye For Now',
    'CU':   'See You',
    'CYL':  'See You Later',
    'GTG':  'Got to Go',
    'OMW':  'On My Way',
    'RN':   'Right Now',
    'TTYL': 'Talk To You Later',
    'TYT':  'Take Your time',
    'CC':   'Carbon Copy',
    'CX':   'Correction',
    'DM':   'Direct Message',
    'FB':   'Facebook',
    '#FBF': 'Flash-Back Friday',
    '#FF':  'Follow Friday',
    'HT':   'Hat Tip',
    'IG':   'Instagram',
    'MT':   'Modified Tweet',
    'OH':   'Overheard',
    'PRT':  'Partial Retweet',
    'RT':   'Retweet',
    'SO':   'Shout Out',
    'AWOL': 'Away While Online',
    'BFF': 'Best Friend Forever',
    'NSFW': 'Not Safe For Work',
    'OG':   'Original Gangster',
    'PSA':  'Public Service Announcement',
    'PDA': 'Public Display of Affection',
    '#TBT': 'Throw-Back Thursday'
    }


    def getAcronyms(self):
        return self.acronyms