
# TODO: make Singleton
class Emoticons:

    emoticons = {
        # Western
        ':-)': 'smile',
        ':)': 'smile',
        ':D': 'smile',
        ':o)': 'smile',
        ':]': 'smile',
        ':3': 'smile',
        ':c)': 'smile',
        ': >': 'smile',
        '=]': 'smile',
        '8)': 'smile',
        '=)': 'smile',
        ':}': 'smile',
        ':^': 'smile',
        '):': 'smile',
        ':-))': 'happy',
        ':-D': 'laughing',
        '8-D': 'laughing',
        '8D': 'laughing',
        'x-D': 'laughing',
        'xD': 'laughing',
        'X-D': 'laughing',
        'XD': 'laughing',
        '=-D': 'laughing',
        '=D': 'laughing',
        '=-3': 'laughing',
        '= 3': 'laughing',
        'B^D': 'laughing',
        '>:[': 'sad',
        ':-(': 'sad',
        ':(': 'sad',
        ':-c': 'sad',
        ':c': 'sad',
        ':-<': 'sad',
        ':<': 'sad',
        ':-[': 'sad',
        ':[': 'sad',
        ':{': 'sad',
        ';(': 'sad',
        ':-||': 'angry',
        ':@': 'angry',
        '>:(': 'angry',
        ':\'-(': 'crying',
        ':\'(': 'crying',
        ':\'-)': 'happiness',
        ':\')': 'happiness',
        'D:<': 'horror',
        'D:': 'horror',
        # 'D8':
        'D;': 'disgust',
        # 'D=':
        # 'DX':
        'v.v': 'sadness',
        '>:O': 'surprise',
        ':-O': 'surprise',
        ':O': 'surprise',
        ':-o': 'surprise',
        ':o': 'surprise',
        '8-0': 'surprise',
        'O_O': 'shock',
        'o-o': 'shock',
        'O_o': 'shock',
        'o_O': 'shock',
        'o_o': 'shock',
        'O-O': 'shock',
        '=o=': 'yawn',
        ':*': 'kiss',
        ':-*': 'kiss',
        ':^*': 'kiss',
        ';-)': 'wink',
        ';)': 'wink',
        '*-)': 'wink',
        '*)': 'wink',
        ';-]': 'wink',
        ';]': 'wink',
        ';D': 'wink',
        ';^': 'wink',
        '):-,': 'wink',
        '>:P': 'tongue',
        ':-P': 'playful',
        ':P': 'playful',
        'X-P': 'playful',
        'x-p': 'playful',
        'xp': 'playful',
        'XP': 'playful',
        ':-p': 'playful',
        ':p': 'playful',
        '=p': 'playful',
        ':-b': 'playful',
        ':b': 'playful',
        'd:': 'playful',
        '>:\\': 'skeptical',
        '>:/': 'skeptical',
        ':-/': 'skeptical',
        ':-.': 'skeptical',
        ':/': 'skeptical',
        ':\\': 'skeptical',
        '=/': 'skeptical',
        '=\'': 'skeptical',
        ':L': 'skeptical',
        '=L': 'skeptical',
        ':S': 'annoyed',
        '>.<': 'annoyed',
        ':|': 'indecision',
        ':-|': 'indecision',
        ':$': 'embarrassed',
        ':-X': 'sealed lips',
        ':X': 'sealed lips',
        ':-#': 'sealed lips',
        ':#': 'sealed lips',
        'O:-)': 'angel',
        '0:-3': 'angel',
        '0:3': 'angel',
        '0:-)': 'angel',
        '0:)': 'angel',
        '0;^)': 'angel',
        '>:)': 'evil',
        '>;)': 'evil',
        '>:-)': 'evil',
        '}:-)': 'devilish',
        '}:)': 'devilish',
        '3:-)': 'devilish',
        '3:)': 'devilish',
        'o/\o': 'high five',
        '^5': 'high five',
        '>_> ^ ^ <_<': 'high five',
        '|;-)': 'cool',
        '|-O': 'cool',
        ':-J': 'tongue-in-cheek',
        ':-&: &': 'tongue-tied',
        '#-)': 'partied all night',
        '%-)': 'drunk',
        '%)': 'drunk',
        ':-###..': 'being sick',
        ':###..': 'being sick',
        '<:-|': 'dumb',
        '\o/': 'cheer',
        '*\\0/*': 'cheerleader',
        '@}-;-\'---': 'rose',
        '@>-->--': 'rose',
        '<3': 'heart',
        '</3': 'broken-heart',
        # some Eastern
        '(>_<)': 'troubled',
        '( > _ <)>': 'troubled',
        '(\';\')': 'baby',
        '(_^;)': 'embarrassed',
        '(-_-;)': 'nervous',
        '(~_~;)': 'nervous',
        '^^;': 'shy',
        '^_^;': 'shy',
        '(^.^#)': 'shy',
        '(^ ^;)': 'shy',
        '(-_ -)zzz': 'sleeping',
        '(^_-)': 'wink',
        '((+_ +))': 'confused',
        '(+o+)': 'confused',
        '^_^': 'joyful',
        '(^_^)/': 'joyful',
        '(^O^)/': 'joyful',
        '(^o^)/': 'joyful',
        '(^^)/': 'joyful',
        '^^': 'joyful',
        '(__)': 'respect',
        '_(._.)_': 'respect',
        '_(_^_)_': 'respect',
        '_<(__)>': 'respect',
        '<m(__)m>': 'respect',
        'm(__)m': 'respect',
        '(\'_\')': 'sad',
        '(/_;)': 'sad',
        '(T_T)': 'sad',
        '(;_;)': 'sad',
        '(;_; ': 'sad',
        '(;_:)': 'sad',
        '(;O;)': 'sad',
        '(:_;)': 'sad',
        '(ToT)': 'sad',
        ';_;': 'sad',
        ';-;': 'sad',
        ';n;': 'sad',
        ';;': 'sad',
        'Q.Q': 'sad',
        'T.T': 'sad',
        'QQ': 'sad',
        'Q_Q': 'sad',
        '(-.-)': 'shame',
        '(-_ -)': 'shame',
        '(=_=)': 'tired',
        '=^_^=': 'cat',
        '(..)': 'looking down',
        '(._.)': 'looking down',
        '(?_?)': 'confusion',
    } #dictionary of emoticons

    def getDictionary(self):
        return self.emoticons

    # print(emoticons['^^'])